language: go

sudo: required

go:
  - "1.14.x"

services:
- docker

env: GO111MODULE=on

install:
  - go mod download
  - git submodule update --init

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv

script:
 - go test -race -failfast -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build