language: go
sudo: required
go:
  - "1.12"
services:
- docker
env: GO111MODULE=on

env:
  global:
    - GOTFLAGS="-race"
    - IPFS_PATH=/tmp/ipfs
  matrix:
    - BUILD_DEPTYPE=gomod

script:
 - go test -race -failfast -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
